name: ROM BUILDER

on:
    push:
       branches:
          - main

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - name: Display Run Parameters
      run: |
        echo "::group::User Environment Variables"
        echo "PWD: $PWD"
        ls .
        echo "::endgroup::"
 
    # You might want to Checkout your repo first, but not mandatory
    - name: Check Out
      uses: actions/checkout@v3
    # Cleanup The Actions Workspace Using Custom Composite Run Actions
    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main
      # That's it! Now use your normal steps
    - name: Prepare setup
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo apt-get install -y git sudo neofetch unzip apt-utils curl wget 
        wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip && unzip platform-tools-latest-linux.zip -d /tmp/ && export PATH="/tmp/platform-tools:$PATH"
        cd /tmp && git clone https://github.com/akhilnarang/scripts   && cd scripts && bash setup/android_build_env.sh
        curl https://storage.googleapis.com/git-repo-downloads/repo > /tmp/bin/repo  && chmod a+x /tmp/bin/repo && export PATH="/tmp/bin:$PATH"
         